#!/bin/bash
APPDIR="$(dirname "$(readlink -f "$0")")"

LOADERS_CACHE="${APPDIR}/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache"
TMP_LOADERS_CACHE="$(mktemp)"  # Create a temporary file
cp "$LOADERS_CACHE" "$TMP_LOADERS_CACHE"
sed -i -e "s#/usr#${APPDIR}/usr#g" "$TMP_LOADERS_CACHE"

# libs
export LD_LIBRARY_PATH="${APPDIR}/usr/lib:${LD_LIBRARY_PATH}"

# icons etc.
export XDG_DATA_DIRS="${APPDIR}/usr/share:${XDG_DATA_DIRS}"

# point to the local pixbuf cache
export GDK_PIXBUF_MODULE_FILE="${TMP_LOADERS_CACHE}"

# PLplot
export PLPLOT_LIB="${APPDIR}/usr/share/plplot5.15.0"
export PLPLOT_DRV_DIR="${APPDIR}/usr/lib/plplot5.15.0/drivers"

exec $APPDIR/usr/bin/UncertRadio "$@"

rm -f "$TMP_LOADERS_CACHE"