#!/bin/bash

APPDIR="$(dirname "$(readlink -f "$0")")"

# libs
export LD_LIBRARY_PATH="$APPDIR/usr/lib:${LD_LIBRARY_PATH}"

# icons etc.
export XDG_DATA_DIRS="${APPDIR}/usr/share:${XDG_DATA_DIRS}"

# PLplot (wip: buggy)
export PLPLOT_DATA_DIR="${APPDIR}/usr/share/plplot5.15.0"

exec $APPDIR/usr/bin/UncertRadio